# Builds the rust binaries for the lambda functions cloud-main, cloud-bucket-cleaner and cloud-sine-generator
# The target is cached with a key consisting of the cargo.lock file and the main.rs files of each lambda.
# The binaries are then uploaded as artifacts in order to be used by terraform.

name: Rust

on: 
  workflow_dispatch:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.yml'
      - '**.tf'
  
env:
  TF_VAR_TABLE_NAME: cloud-wave-file 
  TF_VAR_GLOBAL_INDEX: cloud-date-time-index
  TF_VAR_REACT_BUCKET: cloud-react-website-bucket
  TF_VAR_BUCKET_NAME: cloud-wave-file-bucket
  TF_VAR_GENERATOR_LAMBDA: cloud-sine-generator
  TF_VAR_CLEANER_LAMBDA: cloud-bucket-cleaner
  TF_VAR_MAIN_LAMBDA: cloud-main
  ARTIFACT_PATH: lambda-binaries
  BIN_NAME: bootstrap.zip
  TF_VAR_FRONTEND_BUILD_SCRIPT: set_env_vars_for_frontend_build.sh

jobs:

  checkout-repository:

    runs-on: self-hosted
    steps:
      - name: print event info
        run: echo '${{ toJSON(github.event) }}'
        
      - name: Checkout Repo
        uses: actions/checkout@v3
  
  test:
    runs-on: macos-12
    needs: checkout-repository
    steps:
      - uses: actions/checkout@v3
      - name: Test Sine Generator Crate
        run: |
          cd sine_generator
          cargo test
      - name: Try Cache
        id: cache-test
        uses: actions/cache@v3
        env:
          cache-name: cache-rust-deps-test
        with:
          path: ./target
          key: test-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('**/main.rs') }}
          restore-keys: |
            build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
            build-${{ env.cache-name }}
      - name: Test Lambdas
        run: cargo test --release

  build-cache-and-lambda:
    runs-on: macos-12
    needs: test
    outputs:
      is-cache-hit: ${{ steps.cache-target.output.cache-hit }}

    steps:
      - uses: actions/checkout@v3
      - name: Try Cache
        id: cache-target
        uses: actions/cache@v3
        env:
          cache-name: cache-rust-deps
        with:
          path: ./target
          key: build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('**/main.rs') }}
          restore-keys: |
            build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
            build-${{ env.cache-name }}
      - name: Build Lambdas
        run: |
          brew tap cargo-lambda/cargo-lambda
          brew install cargo-lambda
          cargo lambda build --release --output-format Zip
      
  upload-artifacts:
    
    # only upload artifacts if there was a cache miss
    #if: needs.build-cache-and-lambda.outputs.is-cache-hit == 'false' 
    
    env:
      BIN_PATH: "target/lambda"
      
    needs: build-cache-and-lambda
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_PATH }}
          path: |
            ${{ env.BIN_PATH }}/${{ env.TF_VAR_MAIN_LAMBDA }}/${{ env.BIN_NAME }}
            ${{ env.BIN_PATH }}/${{ env.TF_VAR_CLEANER_LAMBDA }}/${{ env.BIN_NAME }}
            ${{ env.BIN_PATH }}/${{ env.TF_VAR_GENERATOR_LAMBDA }}/${{ env.BIN_NAME }}
            
        
  terraform:
    name: 'Terraform'
    runs-on: macos-12
    environment: production
    needs: upload-artifacts
    env:  
      # Sadly, I cannot use envs to declare other envs, so I have to hardcode the paths
      TF_VAR_CLEANER_LAMBDA_BOOTSTRAP: ../lambda-binaries/cloud-bucket-cleaner/bootstrap.zip
      TF_VAR_GENERATOR_LAMBDA_BOOTSTRAP: ../lambda-binaries/cloud-sine-generator/bootstrap.zip
      TF_VAR_MAIN_LAMBDA_BOOTSTRAP: ../lambda-binaries/cloud-main/bootstrap.zip


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v3 # not specifying which artifact downloads all artifacts
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: List directory # for debugging
      run: |
        ls ${{ env.ARTIFACT_PATH }}/${{ env.TF_VAR_MAIN_LAMBDA }}
        ls ${{ env.ARTIFACT_PATH }}/${{ env.TF_VAR_MAIN_LAMBDA }}
        ls ${{ env.ARTIFACT_PATH }}/${{ env.TF_VAR_MAIN_LAMBDA }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=infra init 

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      continue-on-error: true   
      run: terraform -chdir=infra fmt -check infra 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=infra plan -input=false  

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform -chdir=infra apply -auto-approve -input=false
        
  build-frontend:
    needs: terraform
    runs-on: macos-12
    
    steps:
    - name: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: build
      run: sh builds/${{ env.TF_VAR_FRONTEND_BUILD_SCRIPT }}
#    - uses: actions/setup-python@v3
#      with:
#        python-version: "3.8"
#    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: upload to bucket
      run: aws s3 cp cloud_s3_frontend/build  s3://${{ env.TF_VAR_REACT_BUCKET }} --recursive
      
      
    
